name: "Pipeline Sandbox Review"
description: "Submit your Pipeline sandbox project for review"
body:
  - type: dropdown
    id: project
    attributes:
      label: Project
      description: Select your project.
      options:
        - Car Charging Reservation System
        - Budget OK
        - CTF
        - Ghibli Encyclopedia
        - Veg Finder
        - Flight Reservation System (FRS)
        - Event Sourcing Learning Application
        - Project Powerhouse
    validations:
      required: true
  - type: dropdown
    id: course
    attributes:
      label: Course
      description: Course this submission is for.
      options:
        - Pipeline Accelerator
      default: 0
    validations:
      required: true
  - type: dropdown
    id: module
    attributes:
      label: Module
      description: Select the module you are submitting for review.
      options:
        - 01 - Introduction
        - 02 - Commit Stage
        - 03 - Acceptance Stage
        - 04 - QA Stage
        - 05 - Production Stage
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Review Checklist
        *This section will be auto-generated after submission.*
