name: "Module Review"
description: "Submit your sandbox project for review"
body:
  - type: dropdown
    id: project
    attributes:
      label: Project
      description: Select your project.
      options:
        - Car Charging Reservation System
        - Budget OK
        - CTF
        - Ghibli Encyclopedia
        - Veg Finder
        - Flight Reservation System (FRS)
        - Event Sourcing Learning Application
        - Project Powerhouse
    validations:
      required: true
  - type: dropdown
    id: course
    attributes:
      label: Course
      description: Select the course you are submitting for.
      options:
        - Pipeline Accelerator
        - ATDD Accelerator
    validations:
      required: true
  - type: dropdown
    id: module
    attributes:
      label: Module
      description: Select the module you are submitting for review.
      options:
        - 01 - Introduction
        - 02 - Commit Stage
        - 03 - Acceptance Stage
        - 04 - QA Stage
        - 05 - Production Stage
        - 01 - Getting Started
        - 02 - Smoke Tests
        - 03 - E2E Tests
        - 04 - Architecture - Clients
        - 05 - Architecture - Drivers
        - 06 - Architecture - Channels
        - 07 - Architecture - Use Case DSL
        - 08 - Architecture - Scenario DSL
        - 09 - Architecture - External Stubs
        - 10 - Acceptance Tests
        - 11 - Contract Tests
        - 12 - ATDD - Acceptance Criteria
        - 13 - ATDD - Acceptance Tests
        - 14 - ATDD - Contract Tests
        - 15 - Structural Changes
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Review Checklist
        *This section will be auto-generated after submission.*
